### ISSUE TITLE
Data sufficiency requirements for Monthly methods

### ISSUE THREAD

**Issue by hshaban** [CalTRACK-2/caltrack#66]
<a href="https://github.com/benpolly1"><img src="https://avatars2.githubusercontent.com/u/20544801?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [benpolly1](https://github.com/benpolly1)**
_Monday Jun 26, 2017 at 18:43 GMT_
_Originally opened as https://github.com/impactlab/caltrack/issues/66_

----

In the monthly/data-prep its says:
"12 complete months pre-retrofit for monthly billing data to qualify for estimation or 24 months with up to 2 missing values from different, non-contiguous months"

In the monthly/savings-calculations it says the following: "Final data sufficiency qualification check: All qualifying sites must have at least 12 months of contiguous UPDm values in the pre-intervention series and at least 12 months of contiguous post-intervention UPDm values starting with the month after work_end_date."

Is the month/data-prep section outdated or should the monthly/savings-calculations be modified as follows? 

"Final data sufficiency qualification check: All qualifying sites must have at least 12 months of contiguous UPDm values **_or 24 months with up to 2 missing values from different, non-contiguous months_** in the pre-intervention series and at least 12 months of contiguous post-intervention UPDm values starting with the month after work_end_date."

If changes are made, may need to revisit the following section in monthly/savings-calculations: "Estimate second-stage gross savings quantities based on selected first stage pre- and post-intervention models"

**Comment by danrubado** [comment]
This issue is related to issue #68 - Specify maximum baseline and reporting period lengths. As stated in my comment on issue #68, Energy Trust has a preference for using a maximum of 12 months of data in the baseline and reporting periods. Thus, I would suggest the following language: "Final data sufficiency qualification check: All qualifying sites must have 12 months of contiguous UPDm values, with up to 1 missing value, in the pre-intervention time series and 12 months of contiguous post-intervention UPDm values, with up to 1 missing value, starting with the month after work_end_date."

**Comment by hshaban** [comment]
This update has been integrated in CalTRACK 2. Closing this issue
