### ISSUE TITLE
Day-typing for daily methods to better support commercial uses.

### ISSUE THREAD

**Issue by philngo** [CalTRACK-2/caltrack#83]
From @NCIHVAC: I apologize for lobbing in this comment as a mere casual observer rather than somebody who's been actively participating in this conversation. To support commercial uses in the daily methods it may be quite helpful to provide for various groupings of days of the week prior to creating regressions, I've heard this referred to as "day-typing". You could do this several ways. One way would be to run test regressions with various day-type schemes implying different underlying building schedules, then select the scheme that produces the best overall results (another conversation) to build the final regression.

**Comment by philngo** [comment]
Copied from #82.

**Comment by bkoran** [comment]
I assumed that daytyping and hourtying would be included somehow for daily and hourly models; never considered that they wouldn't be.
This paper recommends density-based spatial clustering:
http://auroenergy.com/wp-content/uploads/2016/05/2015_Saurabh_ASHRaE-Trans_Clustering.pdf

**Comment by mcgeeyoung** [comment]
@bkoran Day typing was tested in CalTRACK 1 for daily methods. The test results showed that there was some evidence that model errors would increase for any given day, but that over the course of a year, there was virtually no difference between models that controlled for weekday/weekend versus those that didn't. So, it was decided that there would be no requirement for including day of week as a model term.

**Comment by bkoran** [comment]
@mcgeeyoung , I don't disagree with what you wrote, but I still think it is important, unless the ONLY things the models would be used for is ex post savings estimates:
There may be occasional cases where the savings estimate is affected.  Will anybody know?
Model errors higher, sometimes much higher.
Therefore, the models are proportionally less useful for tracking performance.  Since the standard errors are much higher, deviations in performance, e.g. via tracking standardized residuals, will not be very useful.
Perhaps most important, energy use trends in the baseline can change sign.  Many buildings have gradual changes in energy use.  Sometimes they are seasonal, sometimes not.  When they are seasonal, it is useful to treat holidays as a daytype.  Maybe an combination AR model would also work.  But for purposes of estimating savings for commercial programs, I have been pushing the concept of understanding baseline energy use trends.  I simply look at whether a time series of residuals has a statistically significant slope.  But this slope is dependent upon getting holidays correct, if not daytypes in general.  Ignoring daytypes can result in a statistically significant slope changing sign.  This definitely affects savings estimates if, as I suggest, we estimate savings relative to the 'normalized' rate of energy use at the end of the baseline.

**Comment by bkoran** [comment]
It probably goes without saying, but daytyping is much more important for commercial buildings than for residential.  So if the CalTRACK 1 testing was just for residential, it needs to be revisited.

Here's an example of a real building, with and without daytyping. 
Savings with/without daytyping: 
12.6%/13.1%  small change; about 5% higher savings.
CV(RMSE) with/without daytyping:
8.9%/30.2%   huge difference in the ability to detect savings or have a reasonable precision.

Using a rough approximation for uncertainty, the relative precision goes from 
8% to 26% at the 90% confidence level.

I've attached a picture of the model without daytyping to show that, appearance-wise, it seems absurd.
Following are the time series of residuals for the model with daytyping and the model without.
![model without daytyping](https://user-images.githubusercontent.com/36519050/37448451-541adc66-281e-11e8-9256-490a76d3be2a.jpg)
![residuals history with daytypes](https://user-images.githubusercontent.com/36519050/37448452-543d7488-281e-11e8-8711-4b6e910c3aa3.jpg)
![residuals history without daytypes](https://user-images.githubusercontent.com/36519050/37448453-5464b07a-281e-11e8-8dfe-a5ac8a08fbf7.jpg)

**Comment by mcgeeyoung** [comment]
These are great examples. The funny thing about daytyping is that while you get a bit more noise on individual projects, over a portfolio, as long as the usage distribution doesn't materially change from pre to post, that is, as long as the building continues to have the same general operating hours, the actual savings values turn out about the same. This only holds if you are paying out savings no more frequently than monthly. Obviously, as we get into hourly (time and locational savings), daytyping itself will be INSUFFICIENT! Let's open up a separate issue for this so we can consider whether we want to add some guidance to daily methods to include this as an option and then certainly revisit it when we get to hourly.
