### ISSUE TITLE
Non-Routine Adjustments

### ISSUE THREAD

**Issue by steevschmidt** [CalTRACK-2/caltrack#84]
From the [Weekly CalTRACK Update](http://www.caltrack.org/project-updates/week-six-caltrack-update):

> At a general level, CalTRACK methods shy away from stipulating methods for non-routine adjustments, as these tend to demand substantial additional effort and may require additional data that would run contrary to the premise of using CalTRACK methods in the first place.

My understanding is that NRAs are quite common in Commercial Building EE, so I don't understand why they wouldn't be considered for residential buildings in P4P programs.

A recent example is a home with flooding damage, which ran pumps and fans continuously for several weeks. Since this was continuous use, the additional electric load is easily quantified and documented with smart meter data, resulting in an incremental amount of kWhs above "normal use" during a specific period.

Why wouldn't CalTRACK methods allow for this case, and others that can be similarly quantified? 

I believe we could develop simple protocols (proof of NRA, quantification of NRA, limited time period of NRA, etc.) which would allow for inclusion of more buildings in P4P programs, instead of adopting an approach that may exclude more buildings than necessary -- to the detriment of the aggregators and overall claimed savings.

**Comment by mcgeeyoung** [comment]
This is a policy decision. In commercial P4P, with few assets, it makes more sense to do NRAs. CalTRACK 1.0 took up this issue and allowed for projects with +/- 50% savings to be flagged for review and removed from a portfolio. Doing commercial-style NRAs on residential buildings would be really expensive relative to the savings that are happening and sort of antithetical to the premise of residential P4P. In practice, NRA's tend to be highly litigated and it usually has very little to do with methods.

**Comment by mgwyman** [comment]
As a program sponsor/designer I agree with McGee's recommendation. I'm anticipating NRAs will be a negotiated program rule with our P4P participants prior to the launch of our pilot, with the likely outcome that a tbd range of outlier projects will be removed from performance based cohorts, as opposed to performing NRAs on each and every project with unusual usage events.

**Comment by hanjame** [comment]
What is the method that will be used to make determinations on outliers? Would a Mean Absolute Deviation (MAD) be a good choice?

**Comment by BruceMast** [comment]
I need to support Steve's request for a more refined approach to NRAs. Simply dropping projects from aggregator cohorts is a fairly blunt-instrument adjustment strategy. It may be acceptable for programs with short performance periods because the frequency of NRAs would presumably be low enough to ignore. But I'm aware of at least one program sponsor that is contemplating a performance period of 3-5 years. In that scenario, dropping projects with non-routine events could result in substantial attrition to an aggregator's portfolio, with several unwelcome consequences:
1. Strands the aggregator's investment in those projects
2. Introduces risk to an aggregators's portfolio that is hard to quantify, thereby increasing the cost of insuring the portfolio and/or treating it as a business asset for financing purposes
3. Sets P4P energy efficiency programs in opposition to other public benefit programs that systematically trigger non-routine events (e.g., distributed PV, electric vehicle charging)

It would be helpful to have some standardized approaches to adjusting for the most important non-routine events without getting into the weeds of adjusting for every little thing.

**Comment by mcgeeyoung** [comment]
This issue will likely be taken up by the GRID working group. Closing for now.
