### ISSUE TITLE
Uncertainty of time-aggregated savings from hourly methods

### ISSUE THREAD

**Issue by hshaban** [CalTRACK-2/caltrack#92]
Estimating time-aggregated uncertainty for hourly models is challenging due to residual autocorrelation and no practical methods have been rigorously tested yet using hourly data. A good starting point would be the evaluation of existing formulations and comparing to bootstrapping, similar to [Koran (2017)](http://www.iepec.org/2017-proceedings/polopoly_fs/1.3718217.1502901133!/fileserver/file/796649/filename/024.pdf)

**Comment by andrewleepge** [comment]
How is uncertainty dealt with in general when estimating hourly payable savings? For example, if estimated savings for a given hour are not statistically significant, are they valued at zero?

If the assumed method simply calls for taking hourly point estimates and adding them up to generate an aggregate savings number, correlated errors may not pose a relevant problem because serial correlation is not supposed to systematically affect the coefficient estimates. My understanding is that serial correlation leads to smaller standard errors, which in turn generates false precision. But the simple act of adding up point estimates won’t yield a standard error anyway, regardless of whether the errors are correlated or uncorrelated.

To the extent that standard errors are needed, one solution would be to simply generate both aggregate savings and their associated standard errors using the daily or monthly method. That sidesteps the threat of correlated hourly errors altogether. Now there is still a question of how much “better” daily or monthly methods are, or if they are also susceptible to serial correlation, but it seems like that can be better understood through model testing.

But once we have our best estimate of aggregate savings and the associated standard error, we would still need to know when during the day those savings occur. The hourly method could be used to determine the percentage of savings that occur during specific time periods, and that percentage could be applied to the aggregated savings that were derived from the daily or monthly method. Under this approach, the hourly method would only really be used to divide the aggregate savings into peak savings and off-peak savings.

**Comment by steevschmidt** [comment]
> ....we would still need to know when during the day those savings occur. 

Agreed -- this seems very challenging.
(Do we have any results yet for the hourly model applied to residential buildings?)
Perhaps more challenging, in order to measure peak vs off-peak savings by hour we should know which hourly loads need to be weather normalized, and which do not.
A simple example: two homes in Fresno have large hourly loads for both A/C and pool pumps. A/C loads need to be weather normalized, whereas pool pump loads should not be. One home runs their pool pump only during off-peak hours but their A/C runs during peak hours, while the other home does the opposite.
Do we think the hourly model could distinguish these two cases?
P4P programs that target either pool pumps or HVAC would expect so, if their payments were tied to this analysis.
